services:

    dmkorocrm_contact.calendar_provider:
        class: DMKOroCRM\Bundle\ContactBundle\Provider\BirthdayCalendarProvider
        arguments:
            - "@oro_entity.doctrine_helper"
            - "@oro_security.acl_helper"
            - "@dmkorocrm_contact.task.normalizer"
            - "@translator"
        tags:
            - { name: oro_calendar.calendar_provider, alias: birthdays }

    dmkorocrm_contact.task.normalizer:
        class: DMKOroCRM\Bundle\ContactBundle\Provider\BirthdayCalendarNormalizer
        arguments:
            - "@translator"
            - "@oro_reminder.entity.manager"

    dmkorocrm_contact.calendar_add.widget_provider.actions:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - dmkorocrm_contact_calendar_add_button
            - dmkorocrm_contact_calendar_add_link
        tags:
            - { name: oro_ui.view_action_provider, group: activity, priority: 100 }
            - { name: oro_ui.update_action_provider, group: activity, priority: 100 }
